apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: banyan-mysql
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: centos/mysql-57-centos7
          env:
            - name: MYSQL_USER
              value: banyan
            - name: MYSQL_PASSWORD
              value: banyan
            - name: MYSQL_ROOT_PASSWORD
              value: banyan
            - name: MYSQL_DATABASE
              value: banyan
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
  - kind: Service
    apiVersion: v1
    metadata:
      name: mysql
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
    spec:
      ports:
        - name: mysql
          port: 3306
          targetPort: 3360
      selector:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: database
