apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: banyan
  labels:
{{ include "banyan.labels" . | indent 4 }}
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "banyan.argonauts.dev"
    resources:
      - domains
    verbs:
      - '*'