apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "banyan.fullname" . }}
  labels:
{{ include "banyan.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: banyan
subjects:
  - kind: ServiceAccount
    name: {{ include "banyan.fullname" . }}
    namespace: {{ .Release.Namespace }}