---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: banyan
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: 
      - "" # "" indicates the core API group
    resources: 
      - "configmaps"
    verbs: 
      - "*"