---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "banyan.fullname" . }}
  namespace: {{.Release.Namespace}}
subjects:
- kind: ServiceAccount
  name: {{ include "banyan.fullname" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: banyan