apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banyan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "banyan.labels" . | indent 4 }}
name: {{ include "banyan.fullname" . }}